#数据源配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: XXX
      password: XXX

#视图解析器配置
  mvc:
    view:
      prefix: classpath*:/templates/
      suffix: .html
      #开启restful
    hiddenmethod:
      filter:
        enabled: true

#评论邮件回复配置
  mail:
    default-encoding: utf-8
# 主机地址
    host: smtp.163.com
# 邮箱名
    username: XXX
# 授权码（不是密码）
    password: XXX
# redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 100
        max-wait: 1
        max-idle: 10
        min-idle: 0
    timeout: 1000
    password: XXX

#mybatis-plus配置
mybatis-plus:
  configuration:
    #添加日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
#mybatis分页插件配置
pagehelper:
  #设置参数合理化
  reasonable: true

#日志配置
logging:
  lever:
    root: info
    com.heshijia: debug
  #配置日志文件存放路径
  file:
    path: log/blog/



